name: Mi Demo con React
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código
        uses: actions/checkout@v4
      - name: Instalar Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalar Dependencias
        run: npm ci
      - name: Ejecutar pruebas
        run: npm test